### ISSUE TITLE
Limitar la complejidad de las consultas mediante OpenAI

### ISSUE THREAD

**Issue by Eguiarte239** [Eguiarte239/Schedule-Builder#17]
# Requerimientos
- Es necesario limitar la complejidad de las consultas SQL que se generen por medio de la api de OpenAI.
- Se puede intentar modificar el prompt para limitar la complejidad de las consultas.

**Comment by GALL1T0** [comment]
En conjunto con sarahí se limitó a no hacer JOINS innecesarios y evitar hacer mas de 1 Join por consulta
